apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: rms-bff
  namespace: rms
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rms-bff
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75 # Escala automaticamente ao atingir 75% de uso de CPU