version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - default
    restart: unless-stopped

  api:
    container_name: api-container
    image: rms-backend-fase01
    restart: always
    ports:
      - "3000:3000"
    links:
      - postgres
    depends_on:
      - postgres

networks:
  default:
    driver: bridge

volumes:
  postgres:
