apiVersion: v1
kind: ConfigMap
metadata:
  name: rms-bff-config
  namespace: rms
  labels:
    app: rms-bff
data:
  DB_HOST: "postgres" # Deve refletir o nome do Service do PostgreSQL
  DB_PORT: "5432"
  DB_USERNAME: "pguser"
  DB_PASSWORD: "pgpwd"
  DB_NAME: "rms"
  DB_SSL: "false"
  ACCESS_TOKEN_MERCADOPAGO: ""
  USER_ID_MERCADOPAGO: ""
  EXTERNAL_POS_ID_MERCADOPAGO: ""
  WEBHOOK_URL_MERCADOPAGO: ""
  IDEMPOTENCY_KEY_MERCADOPAGO: ""