apiVersion: apps/v1
kind: Deployment
metadata:
  name: rms-bff
  namespace: rms
  labels:
    app: rms-bff
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rms-bff
  template:
    metadata:
      labels:
        app: rms-bff
    spec:
      containers:
      - name: rms-bff
        image: rms-bff:latest
        imagePullPolicy: IfNotPresent # Necessário definir "IfNotPresent" ao utilizar o Kubernetes do Docker Desktop para evitar erros "ImagePullBackOff" ao criar os Pods
        envFrom:
          - configMapRef:
              name: rms-bff-config
        ports:
        - containerPort: 3000
        resources:
          # You must specify requests for CPU to autoscale
          # based on CPU utilization
          requests:
            cpu: "250m"
            memory: "512Mi"