apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: rms-bff
  namespace: rms
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rms-bff # name do Deployment a ser escalado automaticamente pelo HPA
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
