apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: rms
type: Opaque
data:
  # Dica: Você pode usar o https://www.base64encode.org/ para converter de/para Base64
  POSTGRES_USER: cGd1c2Vy
  POSTGRES_PASSWORD: cGdwd2Q=
