apiVersion: v1
kind: ConfigMap
metadata:
  name: rms-bff-config
  namespace: rms
  labels:
    app: rms-bff
data:
  DB_HOST: "" # Endpoint do banco de dados RDS (PostgreSQL) na AWS
  DB_PORT: ""
  DB_NAME: ""
  DB_SSL: ""
  ENABLE_AMZ_COGNITO_CIAM: "false"
  COGNITO_USER_POOL_ID: ""
  COGNITO_CLIENT_ID: ""
  ENABLE_MERCADOPAGO: "false"
  USER_ID_MERCADOPAGO: ""
  EXTERNAL_POS_ID_MERCADOPAGO: ""
  WEBHOOK_URL_MERCADOPAGO: ""
  IDEMPOTENCY_KEY_MERCADOPAGO: "a005986e-f97c-4274-91cf-b32d2672824f"