apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: rms
spec:
  provider: aws
  secretObjects:
    - secretName: db-bff-secret # Nome do Secret que será montado automaticamente contendo os segredos do AWS Secrets Manager
      type: Opaque
      data:
        - objectName: username
          key: username
        - objectName: password
          key: password
    - secretName: mercadopago-secret # Nome do Secret que será montado automaticamente contendo os segredos do AWS Secrets Manager
      type: Opaque
      data:
        - objectName: ACCESS_TOKEN_MERCADOPAGO
          key: ACCESS_TOKEN_MERCADOPAGO
  parameters:
    # Informe abaixo no campo objectName o(s) Nomes do Segredos do AWS Secrets Manager que deseja acessar
    objects: |
      - objectName: "nome/Segredo/Aqui"
        objectType: "secretsmanager"
        jmesPath:
          - path: "username"
            objectAlias: "username"
          - path: "password"
            objectAlias: "password"
      - objectName: "nome/Segredo/Aqui"
        objectType: "secretsmanager"
        jmesPath:
          - path: "ACCESS_TOKEN_MERCADOPAGO"
            objectAlias: "ACCESS_TOKEN_MERCADOPAGO"
