apiVersion: v1
kind: Service
metadata:
  name: rms-bff
  namespace: rms
  labels:
    app: rms-bff
spec:
  selector:
    app: rms-bff
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80 # Porta no Load Balancer
      targetPort: 3000 # Porta do Pod