name: GitHub Actions
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - run: make test
  Lint:
    runs-on: ubuntu-latest
    steps:
      - run: make lint
